### ISSUE TITLE
Daks brokerbot isn't shown in the analytics in the apps

### ISSUE THREAD

**Issue by Jennykoz** [aktionariat/subgraph#29]
it seems the graph is retrieving the old brokerbot with the XCHF
we should show the data of the broketbot here
<img width="392" alt="image" src="https://github.com/aktionariat/subgraph/assets/100677407/31ba6bba-62e8-42d9-9733-173f9c260a15">

@KostasZav fyi

**Comment by KostasZav** [comment]
Looks like this is fixed. @Jennykoz can you please verify and close this ticket if that's the case? Thanks
